# Site settings
title: Clément Fleury
description: Clément Fleury
favicon: /assets/img/favicon.ico
baseurl: https://fleuryc.github.io
url: https://fleuryc.github.io
rss_url: /pages/atom.xml
google_analytics: UA-41186741-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Clément Fleury
  title: Full stack Web Developer & DevOps
  address: Paris, France
  email: clement.fleury@gmail.com
  link: http://clementfleury.me
  weibo:
  github: fleuryc
  linkedin: clementfleury
  twitter: fleurycassets/img/android-chrome-192x192.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Alter Solutions Engineering
      location: Versailles, France
      title: Senior Full Stack Web Developer, Project Manager, Team Leader, DevOps
      started: 2011
      duration: (2011 - Present)
      description: I do many things...
  educationHistory:
    - education1:
      organization: ENSIMAG (Ecole Nationale Supérieure d'Informatique et Mathématiques appliquées)
      location: Grenoble, France
      degree: MS (Master of Science)
      major: Information, Interaction & Intelligence
      started: 2003
      duration: (2003 - 2006)
      description: I've learn many things...
  languages:
    - language1:
      name: French
      proficiency: Native
    - language2:
      name: English
      proficiency: Proficient
    - language3:
      name: German
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
